export enum TokenizerId {
  NONE = 0,
  GPT2 = 1,
  OPENAI = 2,
  LLAMA = 3,
  NERD = 4,
  NERD2 = 5,
  API_CURRENT = 6,
  MISTRAL = 7,
  YI = 8,
  API_TEXTGENERATIONWEBUI = 9,
  API_KOBOLD = 10,
  CLAUDE = 11,
  LLAMA3 = 12,
  GEMMA = 13,
  JAMBA = 14,
  QWEN2 = 15,
  COMMAND_R = 16,
  NEMO = 17,
  DEEPSEEK = 18,
  COMMAND_A = 19,
  BEST_MATCH = 99,
}

export const TOKENIZER_IDS = [
  TokenizerId.NONE,
  TokenizerId.GPT2,
  TokenizerId.OPENAI,
  TokenizerId.LLAMA,
  TokenizerId.NERD,
  TokenizerId.NERD2,
  TokenizerId.API_CURRENT,
  TokenizerId.MISTRAL,
  TokenizerId.YI,
  TokenizerId.API_TEXTGENERATIONWEBUI,
  TokenizerId.API_KOBOLD,
  TokenizerId.CLAUDE,
  TokenizerId.LLAMA3,
  TokenizerId.GEMMA,
  TokenizerId.JAMBA,
  TokenizerId.QWEN2,
  TokenizerId.COMMAND_R,
  TokenizerId.NEMO,
  TokenizerId.DEEPSEEK,
  TokenizerId.COMMAND_A,
  TokenizerId.BEST_MATCH,
] as const;
